import { useState } from 'react';
import { api, ApiError } from '../api';
import { usePolling } from '../hooks';
import { ErrorBox, Loading } from '../components/ui';
import { useAuth } from '../AuthContext';

type Operator = { id: string; name: string; assignedPaymentAccountIds: string[]; status: 'ACTIVE' | 'DISABLED'; createdAt: number; lastLoginAt: number | null };
type AccountChoice = { adapterId: string; displayName: string; status: string };

export function PaymentOperatorsPage() {
  const { has } = useAuth();
  const { data, error, loading, reload } = usePolling<{ operators: Operator[] }>('/admin/payment-operators', 10000);
  const { data: adapterData } = usePolling<{ adapters: AccountChoice[] }>('/admin/payment-adapters', 10000);
  const accountOptions = (adapterData?.adapters ?? []).filter((account) => account.status !== 'ARCHIVED');
  const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [accounts, setAccounts] = useState<string[]>([]); const [reason, setReason] = useState(''); const [actionError, setActionError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function toggleAccount(account: string) { setAccounts((current) => current.includes(account) ? current.filter((id) => id !== account) : [...current, account]); }
  async function create() { setBusy(true); setActionError(null); setNotice(null); try { await api.post('/admin/payment-operators', { name, password, assignedPaymentAccountIds: accounts, reason }); setName(''); setPassword(''); setAccounts([]); setReason(''); setNotice('Operator created with the selected account assignments.'); reload(); } catch (err) { setActionError(err instanceof ApiError ? err.message : 'Could not create operator'); } finally { setBusy(false); } }
  async function toggle(operator: Operator) { setActionError(null); try { await api.put(`/admin/payment-operators/${operator.id}`, { status: operator.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE', reason: `Operator status changed by ${operator.name}` }); reload(); } catch (err) { setActionError(err instanceof ApiError ? err.message : 'Could not update operator'); } }
  async function saveAssignments(operator: Operator, next: string[]) { try { await api.put(`/admin/payment-operators/${operator.id}`, { assignedPaymentAccountIds: next, reason: 'Payment account assignment changed by SUPER_ADMIN' }); reload(); } catch (err) { setActionError(err instanceof ApiError ? err.message : 'Could not update assignments'); } }
  return <div><h1 className="admin-page-title">Payment Operators</h1><p className="admin-page-sub">SUPER_ADMIN-only operator identity and account assignment. Operators receive platform credentials only; provider secrets never leave the server.</p>{error && <ErrorBox message={error} />}{actionError && <ErrorBox message={actionError} />}{notice && <div className="admin-note">{notice}</div>}{has('PAYMENT_OPERATOR_ADMIN') && <div className="admin-panel"><div className="admin-panel__title">Create payment operator</div><div className="admin-toolbar"><input className="admin-input" placeholder="Operator name" value={name} onChange={(event) => setName(event.target.value)} /><input className="admin-input" type="password" placeholder="Password (min 12 chars)" value={password} onChange={(event) => setPassword(event.target.value)} /></div><p className="admin-page-sub">Assign accounts</p><div className="admin-toolbar">{accountOptions.filter((account) => account.status !== 'ARCHIVED').map((account) => <label key={account.adapterId}><input type="checkbox" checked={accounts.includes(account.adapterId)} onChange={() => toggleAccount(account.adapterId)} /> {account.adapterId} · {account.displayName}</label>)}</div><input className="admin-input" style={{ width: '100%', marginBottom: 10 }} placeholder="Reason" value={reason} onChange={(event) => setReason(event.target.value)} /><button className="admin-btn admin-btn--primary" disabled={busy || name.trim().length < 2 || password.length < 12 || !reason.trim() || accounts.length === 0} onClick={() => void create()}>{busy ? 'Creating…' : 'Create operator'}</button></div>}{loading && !data && <Loading />}{data && <table className="admin-table"><thead><tr><th>Name</th><th>Status</th><th>Assigned accounts</th><th>Action</th></tr></thead><tbody>{data.operators.map((operator) => <tr key={operator.id}><td><strong>{operator.name}</strong><br /><small>{operator.id}</small></td><td>{operator.status}</td><td><div className="admin-toolbar">{accountOptions.map((account) => <label key={account.adapterId}><input type="checkbox" disabled={account.status === 'ARCHIVED' && !operator.assignedPaymentAccountIds.includes(account.adapterId)} checked={operator.assignedPaymentAccountIds.includes(account.adapterId)} onChange={(event) => void saveAssignments(operator, event.target.checked ? [...operator.assignedPaymentAccountIds, account.adapterId] : operator.assignedPaymentAccountIds.filter((id) => id !== account.adapterId))} /> {account.adapterId} · {account.displayName}{account.status === 'ARCHIVED' ? ' · archived' : ''}</label>)}</div></td><td><button className="admin-btn admin-btn--ghost admin-btn--sm" onClick={() => void toggle(operator)}>{operator.status === 'ACTIVE' ? 'Disable' : 'Enable'}</button></td></tr>)}</tbody></table>}</div>;
}
