import { usePolling } from '../hooks';
import { ErrorBox, Loading, StatCard, Badge } from '../components/ui';

interface Overview { totalDeposits: number; totalWithdrawals: number; pendingDeposits: number; pendingWithdrawals: number; failedTransactions: number; activeAdapters: number; disabledAdapters: number; successRate: number | null; failureRate: number | null; pendingVolume: number; operatorWorkload: Array<{ id: string; name: string; status: string; assignedPaymentAccountIds: string[]; openCount: number; underReviewCount: number; oldestOpenAt: number | null }>; }
interface Analytics { deposits: { completedVolume: number; averageProcessingMs: number | null; completed: number; failed: number; pending: number }; withdrawals: { completedVolume: number; averageProcessingMs: number | null; completed: number; failed: number; pending: number }; byAdapter: Array<{ adapterId: string; provider: string; count: number; completed: number; failed: number; volume: number }>; }
interface RiskSignal { id: string; severity: 'INFO' | 'MEDIUM' | 'HIGH' | 'CRITICAL'; kind: string; detail: string; createdAt: number; evidence: Record<string, string | number | boolean>; }

export function PaymentOverviewPage() {
  const overview = usePolling<Overview>('/admin/payment-overview', 10000);
  const analytics = usePolling<Analytics>('/admin/payment-analytics', 15000);
  const risk = usePolling<{ signals: RiskSignal[]; counts: Record<string, number> }>('/admin/payment-risk', 15000);
  return <div>
    <h1 className="admin-page-title">Payment Operations</h1>
    <p className="admin-page-sub">Server-side payment transaction, routing, risk and adapter metrics. Real provider operations remain disabled until configured and approved.</p>
    {overview.error && <ErrorBox message={overview.error} />}{overview.loading && !overview.data && <Loading />}
    {overview.data && <>
      <div className="admin-grid"><StatCard label="Deposits" value={overview.data.totalDeposits} /><StatCard label="Withdrawals" value={overview.data.totalWithdrawals} /><StatCard label="Pending Deposits" value={overview.data.pendingDeposits} /><StatCard label="Pending Withdrawals" value={overview.data.pendingWithdrawals} /><StatCard label="Failed" value={overview.data.failedTransactions} /><StatCard label="Active Adapters" value={overview.data.activeAdapters} /><StatCard label="Disabled / Archived" value={overview.data.disabledAdapters} /><StatCard label="Pending Volume" value={overview.data.pendingVolume} /></div>
      <div className="admin-note">Settlement is webhook-authoritative. A provider request, browser state, admin click, or polling result cannot credit or debit a wallet by itself.</div>
      <section className="admin-panel" style={{ marginTop: 20 }}><h2>Operator workload</h2><p>Global queue visibility is limited to operational counts; provider secrets and player internal identifiers remain excluded.</p><table className="admin-table"><thead><tr><th>Operator</th><th>Status</th><th>Assigned Payment IDs</th><th>Open</th><th>Under review</th><th>Oldest open</th></tr></thead><tbody>{overview.data.operatorWorkload.map((operator) => <tr key={operator.id}><td>{operator.name}<br /><small>{operator.id}</small></td><td>{operator.status}</td><td>{operator.assignedPaymentAccountIds.join(' · ') || 'None'}</td><td>{operator.openCount}</td><td>{operator.underReviewCount}</td><td>{operator.oldestOpenAt ? new Date(operator.oldestOpenAt).toLocaleString() : '—'}</td></tr>)}</tbody></table></section>
    </>}
    {analytics.error && <ErrorBox message={analytics.error} />}{analytics.data && <section className="admin-panel" style={{ marginTop: 20 }}><h2>Settlement analytics</h2><div className="admin-grid"><StatCard label="Deposit settled volume" value={analytics.data.deposits.completedVolume} /><StatCard label="Withdrawal settled volume" value={analytics.data.withdrawals.completedVolume} /><StatCard label="Deposit avg processing" value={analytics.data.deposits.averageProcessingMs == null ? '—' : `${analytics.data.deposits.averageProcessingMs} ms`} /><StatCard label="Withdrawal avg processing" value={analytics.data.withdrawals.averageProcessingMs == null ? '—' : `${analytics.data.withdrawals.averageProcessingMs} ms`} /></div><p>Deposit states: {analytics.data.deposits.completed} completed · {analytics.data.deposits.failed} failed · {analytics.data.deposits.pending} pending. Withdrawal states: {analytics.data.withdrawals.completed} completed · {analytics.data.withdrawals.failed} failed · {analytics.data.withdrawals.pending} pending.</p><table className="admin-table"><thead><tr><th>Adapter</th><th>Provider</th><th>Count</th><th>Completed</th><th>Failed</th><th>Settled volume</th></tr></thead><tbody>{analytics.data.byAdapter.map((row) => <tr key={row.adapterId}><td>{row.adapterId}</td><td>{row.provider}</td><td>{row.count}</td><td>{row.completed}</td><td>{row.failed}</td><td>{row.volume}</td></tr>)}</tbody></table></section>}
    {risk.error && <ErrorBox message={risk.error} />}{risk.data && <section className="admin-panel" style={{ marginTop: 20 }}><h2>Payment risk signals</h2><p>{Object.entries(risk.data.counts).map(([severity, count]) => `${severity}: ${count}`).join(' · ') || 'No stored payment risk signals'}</p>{risk.data.signals.length > 0 && <table className="admin-table"><thead><tr><th>Severity</th><th>Kind</th><th>Detail</th><th>Evidence</th></tr></thead><tbody>{risk.data.signals.slice(0, 20).map((signal) => <tr key={signal.id}><td><Badge tone={signal.severity === 'HIGH' || signal.severity === 'CRITICAL' ? 'red' : 'yellow'}>{signal.severity}</Badge></td><td>{signal.kind}</td><td>{signal.detail}</td><td>{Object.entries(signal.evidence).map(([key, value]) => `${key}=${String(value)}`).join(', ')}</td></tr>)}</tbody></table>}</section>}
  </div>;
}
